

package Gestion;

import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.util.List;
import javax.swing.ImageIcon;


public class Opciones extends javax.swing.JFrame {

      ImagenFondo fondo;
      
    public Opciones() {
                fondo=new ImagenFondo("src/ceti.png");
        this.setContentPane(fondo);
        
        initComponents();
        this.setSize(600,500);
        this.setLocationRelativeTo(null);
        this.setTitle("OPCIONES");
        
        
       // this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jDesktopPane_opiciones = new javax.swing.JDesktopPane();
        jPanel1 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuOrden = new javax.swing.JMenu();
        jmiAgregarPedido = new javax.swing.JMenuItem();
        jmiEliminarPedido = new javax.swing.JMenuItem();
        jmiCancelarOrden = new javax.swing.JMenuItem();
        jMenuProducto = new javax.swing.JMenu();
        jmiModificarProducto = new javax.swing.JMenuItem();
        jmiEliminarProducto = new javax.swing.JMenuItem();
        jMenuMesa = new javax.swing.JMenu();
        jmiCambiarEstadoMesa = new javax.swing.JMenuItem();
        jMenuInventario = new javax.swing.JMenu();
        jmiActualizarInventario = new javax.swing.JMenuItem();
        jimReporteMensual = new javax.swing.JMenuItem();
        jmiReabastecer = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 51));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(17, 17, 56));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jDesktopPane_opiciones.setBackground(new java.awt.Color(0, 102, 102));
        jDesktopPane_opiciones.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jDesktopPane_opiciones.setPreferredSize(new java.awt.Dimension(400, 300));

        jPanel1.setBackground(new java.awt.Color(17, 17, 56));
        jDesktopPane_opiciones.add(jPanel1);
        jPanel1.setBounds(0, 0, 570, 410);

        jPanel2.add(jDesktopPane_opiciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 565, 410));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 480));

        jMenuOrden.setText("Orden");

        jmiAgregarPedido.setText("Agregar Pedido");
        jmiAgregarPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiAgregarPedidoActionPerformed(evt);
            }
        });
        jMenuOrden.add(jmiAgregarPedido);

        jmiEliminarPedido.setText("Eliminar Pedido");
        jMenuOrden.add(jmiEliminarPedido);

        jmiCancelarOrden.setText("Cancelar Orden");
        jmiCancelarOrden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiCancelarOrdenActionPerformed(evt);
            }
        });
        jMenuOrden.add(jmiCancelarOrden);

        jMenuBar1.add(jMenuOrden);

        jMenuProducto.setText("Producto");

        jmiModificarProducto.setText("Modificar Producto");
        jmiModificarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiModificarProductoActionPerformed(evt);
            }
        });
        jMenuProducto.add(jmiModificarProducto);

        jmiEliminarProducto.setText("Eliminar Producto");
        jMenuProducto.add(jmiEliminarProducto);

        jMenuBar1.add(jMenuProducto);

        jMenuMesa.setText("Mesa");

        jmiCambiarEstadoMesa.setText("Cambiar Estado de Mesa");
        jMenuMesa.add(jmiCambiarEstadoMesa);

        jMenuBar1.add(jMenuMesa);

        jMenuInventario.setText("Inventario");

        jmiActualizarInventario.setText("Actualizar Inventario");
        jmiActualizarInventario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiActualizarInventarioActionPerformed(evt);
            }
        });
        jMenuInventario.add(jmiActualizarInventario);

        jimReporteMensual.setText("Generar Reporte Mensual");
        jimReporteMensual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jimReporteMensualActionPerformed(evt);
            }
        });
        jMenuInventario.add(jimReporteMensual);

        jmiReabastecer.setText("Reabastecer Ingrediente");
        jmiReabastecer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiReabastecerActionPerformed(evt);
            }
        });
        jMenuInventario.add(jmiReabastecer);

        jMenuBar1.add(jMenuInventario);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmiCancelarOrdenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiCancelarOrdenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmiCancelarOrdenActionPerformed

    private void jmiActualizarInventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiActualizarInventarioActionPerformed
       ActualizarInventario Actualizar =new ActualizarInventario();
        jDesktopPane_opiciones.add(Actualizar);
        Actualizar.setVisible(true);
    }//GEN-LAST:event_jmiActualizarInventarioActionPerformed

    private void jimReporteMensualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jimReporteMensualActionPerformed
        // TODO add your handling code here:
        ReporteMensual Reporte =new ReporteMensual();
        jDesktopPane_opiciones.add(Reporte);
        Reporte.setVisible(true);
    }//GEN-LAST:event_jimReporteMensualActionPerformed

    private void jmiAgregarPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiAgregarPedidoActionPerformed
        AgregarPedido pedido =new AgregarPedido();
        jDesktopPane_opiciones.add(pedido);
        pedido.setVisible(true);
    }//GEN-LAST:event_jmiAgregarPedidoActionPerformed

    private void jmiModificarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiModificarProductoActionPerformed
        // TODO add your handling code here:
        ModificarProducto modificar =new ModificarProducto();
        jDesktopPane_opiciones.add(modificar);
        modificar.setVisible(true);
    }//GEN-LAST:event_jmiModificarProductoActionPerformed

    private void jmiReabastecerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiReabastecerActionPerformed
        ReabastecerIngredientes Reabastecer =new ReabastecerIngredientes();
        jDesktopPane_opiciones.add(Reabastecer);
        Reabastecer.setVisible(true);
    }//GEN-LAST:event_jmiReabastecerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Opciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Opciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Opciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Opciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Opciones().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPane_opiciones;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuInventario;
    private javax.swing.JMenu jMenuMesa;
    private javax.swing.JMenu jMenuOrden;
    private javax.swing.JMenu jMenuProducto;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JMenuItem jimReporteMensual;
    private javax.swing.JMenuItem jmiActualizarInventario;
    private javax.swing.JMenuItem jmiAgregarPedido;
    private javax.swing.JMenuItem jmiCambiarEstadoMesa;
    private javax.swing.JMenuItem jmiCancelarOrden;
    private javax.swing.JMenuItem jmiEliminarPedido;
    private javax.swing.JMenuItem jmiEliminarProducto;
    private javax.swing.JMenuItem jmiModificarProducto;
    private javax.swing.JMenuItem jmiReabastecer;
    // End of variables declaration//GEN-END:variables
}
